[package]
name = "beefw-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
beefw-common = { path = "../beefw-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "beefw"
path = "src/main.rs"
